backend:
  name: git-gateway
  branch: master

display_url: http://localhost:8000

media_folder: static/images
public_folder: /images

collections:
  - label: "Default Pages"
    name: "defaults"
    delete: false
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/home.md"
        fields:
          - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Visible", name: "visible", widget: "boolean", default: false}
              - {label: "Full width", name: "fullWidth", widget: "boolean", default: false}
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Button text", name: "button", widget: "string", required: false}
              - {label: "Button colour", name: "buttonColour", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
              - {label: "Align", name: "align", widget: "select", options: ["left", "center", "right"], default: "left"}
              - {label: "Background Image", name: "image", widget: "image"}
              - {label: "Image Overlay", name: "overlay", widget: "select", options: ["none", "light", "dark", "primary"], default: "none"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
        
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
          - {label: "Navigation sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}

  - label: "Custom Pages"
    label_singular: "Custom Page"
    name: "customs"
    create: true
    folder: "src/pages/custom"
    slug: "{{slug}}"
    fields:
      - {label: "pageType", name: "pageType", widget: "hidden", default: "standard"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
      - {label: "Navigation sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Settings"
    name: "settings"
    delete: false
    files:
      - label: "Header"
        name: "header"
        file: "src/pages/settings/header.md"
        fields:
          - label: "Header Style"
            name: "headerStyle"
            widget: "select"
            options: ["HeaderMain", "HeaderSlide"]
      
      - label: "Footer"
        name: "footer"
        file: "src/pages/settings/footer.md"
        fields:
          - label: "Footer Background"
            name: "footerBackground"
            widget: "select"
            options: ["dark", "light"]
          