backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/pages/settings.md"
        label: "Settings"
        name: "settings"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "none"}
          - {label: "Title", name: "title", widget: "hidden", default: "Settings"}
          - {label: "Tagline", name: "tagline", widget: "string", required: false}
          - {label: "Show in navigation", name: "nav", widget: "boolean", default: false}
          - label: "Footer Background"
            name: "footerBackground"
            widget: "select"
            options: ["dark", "light", "primary", "danger"]
            default: "dark"