backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "standard"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}