backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "settings"
    label: "Settings"
    files:
      - label: "Global"
        name: "global"
        file: "src/pages/settings.md"
        fields:
          - {label: "Tagline", name: "tagline", widget: "string"}
      - label: "Footer"
        name: "footer"
        file: "src/pages/settings/footer.md"
        fields:
          - label: "Footer Background"
            name: "footerBackground"
            widget: "select"
            options: ["dark", "light", "primary", "danger"]