backend:
  name: git-gateway
  branch: master

display_url: http://localhost:8000

media_folder: static/images
public_folder: /images

collections:
  - label: "Default Pages"
    name: "defaults"
    delete: false
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/default/home.md"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "none"}
          - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Visible", name: "visible", widget: "boolean", default: false}
              - {label: "Full width", name: "fullWidth", widget: "boolean", default: false}
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Button text", name: "button", widget: "string", required: false}
              - {label: "Button link - enter full URL", name: "buttonLink", widget: "string", required: false}
              - {label: "Button colour", name: "buttonColour", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
              - {label: "Align", name: "align", widget: "select", options: ["left", "center", "right"], default: "left"}
              - {label: "Background Image", name: "image", widget: "image"}
              - {label: "Image Overlay", name: "overlay", widget: "select", options: ["none", "light", "dark", "primary"], default: "none"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          
        
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/default/contact.md"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "contact"}
          - {label: "Slug", name: "slug", widget: "hidden", default: "/contact"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
          - {label: "Navigation sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Address", name: "address", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - label: "Thankyou Page"
        name: "thankyou"
        file: "src/pages/default/thankyou.md"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "standard"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Slug", name: "slug", widget: "hidden", default: "/thank-you"}
          - {label: "Show in navigation", name: "nav", widget: "hidden", default: false}
          - {label: "Body", name: "body", widget: "markdown"}

  - label: "Custom Pages"
    label_singular: "Custom Page"
    name: "customs"
    create: true
    folder: "src/pages/custom"
    slug: "{{slug}}"
    fields:
      - {label: "Page Type", name: "pageType", widget: "select", options: ["standard", "menu-only"], default: "standard"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
      - {label: "Navigation sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}
      - {label: "Parent page", name: "parent", widget: "relation", collection: "customs", searchFields: ["title"], valueField: "title", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Settings"
    name: "settings"
    delete: false
    files:
      - label: "Site Settings"
        name: "settings"
        file: "src/pages/settings/settings.md"
        fields:
          - {label: "Settings Page", name: "settingsPage", widget: "hidden", default: true}
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "none"}
          - {label: "Header Style", name: "headerStyle", widget: "select", options: ["HeaderMain", "HeaderSlide"], default: "HeaderMain"}
          - {label: "Header Background", name: "headerBackground", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
          - {label: "Invert", name: "invert", widget: "boolean", default: false}
          - {label: "Footer Background", name: "footerBackground", widget: "select", options: ["dark", "light"], default: "dark"}
          - {label: "Social Links Colour", name: "socialColour", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
          - {label: "Social Links", name: "socialLinks", widget: "list", fields: [{label: "Name", name: "url", widget: "string"}, {label: "Link", name: "link", widget: "string"}]}
          - label: "Floating Button"
            name: "floatingButton"
            widget: "object"
            fields:
              - {label: "Visible", name: "visible", widget: "boolean", default: true}
              - {label: "Type", name: "type", widget: "select", options: ["Phone", "Email"], default: "Phone"}
              - {label: "Colour", name: "colour", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
          