backend:
  name: git-gateway
  branch: master

display_url: https://thkrcms.netlify.com

media_folder: static/images 
public_folder: /images

collections:
  - label: "Default Pages"
    name: "defaults"
    delete: false
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/default/home.md"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "none"}
          - {label: "Home Page", name: "homePage", widget: "hidden", default: true}
          - {label: "Slug", name: "slug", widget: "hidden", default: "/"}
          - {label: "Nav Sort", name: "navSort", widget: "hidden", default: 1}
          - {label: "Menu Title", name: "navTitle", widget: "string", default: "Home"}
          - {label: "Show in menu", name: "nav", widget: "boolean", default: true}
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - {label: "Visible", name: "visible", widget: "boolean", default: true}
              - {label: "Full width", name: "fullWidth", widget: "boolean", default: false}
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Button text", name: "button", widget: "string", required: false}
              - {label: "Button Link", name: "buttonLink", widget: "string", required: false}
              - {label: "Button colour", name: "buttonColour", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
              - {label: "Align", name: "align", widget: "select", options: ["left", "center", "right"], default: "left"}
              - {label: "Background Image", name: "image", widget: "image"}
              - {label: "Image Overlay", name: "overlay", widget: "select", options: ["none", "light", "dark", "primary"], default: "none"}
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Align", name: "contentAlign", widget: "select", options: ["left", "center", "right"], default: "left"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Description", name: "metaDesc", widget: "text", required: false}
          - {label: "Meta Image", name: "metaImage", widget: "image", required: false}

      - label: "Contact"
        name: "contact"
        file: "src/pages/default/contact.md"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "contact"}
          - {label: "Slug", name: "slug", widget: "hidden", default: "/contact"}
          - {label: "Menu Title", name: "menuTitle", widget: "string", default: "Contact"}
          - {label: "Show in menu", name: "nav", widget: "boolean", default: true}
          - {label: "Menu sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}
          - {label: "Page Title", name: "title", widget: "string", default: "Contact"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Address", name: "address", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Description", name: "metaDesc", widget: "text", required: false}
          - {label: "Meta Image", name: "metaImage", widget: "image", required: false}
          - label: "Form"
            name: "form"
            widget: "object"
            fields:
              - {label: "Form Title", name: "formTitle", widget: "string"}
              - {label: "Form Button", name: "buttonText", widget: "string"}
              - {label: "Form Button Colour", name: "buttonColor", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
          - label: "Form Inputs"
            name: "inputs"
            label_singular: "Form Input"
            widget: "list"
            fields:
              - label: "Item"
                name: "item"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Placeholder", name: "placeholder", widget: "string", required: false}
                  - {label: "Type", name: "type", widget: "select", options: ["text", "textarea", "email", "tel", "number"], default: "text"}
                  - {label: "Required", name: "required", widget: "boolean", default: false}

      - label: "Thankyou"
        name: "thankyou"
        file: "src/pages/default/thankyou.md"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "standard"}
          - {label: "Slug", name: "slug", widget: "hidden", default: "/thankyou"}
          - {label: "Nav", name: "nav", widget: "hidden", default: false}
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Meta Description", name: "metaDesc", widget: "text", required: false}
          - {label: "Meta Image", name: "metaImage", widget: "image", required: false}

      - label: "404"
        name: "404"
        file: "src/pages/default/404.md"
        fields:
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "none"}
          - {label: "404 Page", name: "page404", widget: "hidden", default: true}
          - {label: "Slug", name: "slug", widget: "hidden", default: "/404"}
          - {label: "Nav", name: "nav", widget: "hidden", default: false}
          - {label: "Page Title", name: "title", widget: "string", default: "Page not found"}
          - {label: "Body", name: "body", widget: "markdown"}

  - label: "Custom Pages"
    label_singular: "Custom Page"
    name: "customs"
    create: true
    folder: "src/pages/custom"
    slug: "{{slug}}"
    fields:
      - {label: "Page Type", name: "pageType", widget: "select", options: ["standard", "menu-only"], default: "standard"}
      - {label: "Menu Title", name: "menuTitle", widget: "string"}
      - {label: "Show in menu", name: "nav", widget: "boolean", default: true}
      - {label: "Menu sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}
      ## - {label: "Parent page", name: "parent", widget: "relation", collection: "customs", searchFields: ["title"], valueField: "title", required: false}
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Meta Description", name: "metaDesc", widget: "text", required: false}
      - {label: "Meta Image", name: "metaImage", widget: "image", required: false}

  - label: "Settings"
    name: "settings"
    delete: false
    files:
      - label: "Site Settings"
        name: "settings"
        file: "src/pages/settings/settings.md"
        fields:
          - {label: "Settings Page", name: "settingsPage", widget: "hidden", default: true}
          - {label: "Page Type", name: "pageType", widget: "hidden", default: "none"}
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Menu Style", name: "menu", widget: "select", options: ["Standard", "Scroll", "Slide"], default: "Standard"}
              - {label: "Background Colour", name: "background", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
              - {label: "Invert", name: "invert", widget: "boolean", default: false}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
          - {label: "Footer Background", name: "footerBackground", widget: "select", options: ["dark", "light"], default: "dark"}
          - {label: "Social Links Colour", name: "socialColour", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
          - {label: "Social Links", name: "socialLinks", widget: "list", fields: [{label: "Link", name: "link", widget: "string"}]}
          - label: "Floating Button"
            name: "floatingButton"
            widget: "object"
            fields:
              - {label: "Visible", name: "visible", widget: "boolean", default: true}
              - {label: "Type", name: "type", widget: "select", options: ["Phone", "Email"], default: "Phone"}
              - {label: "Colour", name: "colour", widget: "select", options: ["primary", "secondary", "info", "success", "warning", "danger", "dark"], default: "primary"}
          
