backend:
  name: git-gateway
  branch: master

display_url: http://localhost:8000

media_folder: static/images
public_folder: /images

collections:
  - label: "Default Pages"
    name: "defaults"
    delete: false
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/home.md"
        fields:
          # - {label: "Title", name: "title", widget: "string"}
          - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
          - {label: "Show hero", name: "hero", widget: "boolean", default: false}
          - {label: "Full width hero", name: "heroFull", widget: "boolean", default: false}
          - {label: "Hero title", name: "heroTitle", widget: "string"}
        
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
          - {label: "Show hero", name: "hero", widget: "boolean", default: false}
          - {label: "Full width hero", name: "heroFull", widget: "boolean", default: false}
          - {label: "Hero title", name: "heroTitle", widget: "string"}
          - {label: "Navigation sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}

  - label: "Custom Pages"
    label_singular: "Custom Page"
    name: "customs"
    create: true
    folder: "src/pages/custom"
    slug: {{slug}}
    fields:
      - {label: "pageType", name: "pageType", widget: "hidden", default: "standard"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Show in navigation", name: "nav", widget: "boolean", default: true}
      - {label: "Navigation sort number", name: "navSort", widget: "number", min: "2", valueType: "int"}
      - {label: "Show hero", name: "hero", widget: "boolean", default: false}
      - {label: "Full width hero", name: "heroFull", widget: "boolean", default: false}
      - {label: "Hero title", name: "heroTitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Settings"
    name: "settings"
    delete: false
    files:
      - label: "Header"
        name: "header"
        file: "src/pages/settings/header.md"
        fields:
          - label: "Header Style"
            name: "headerStyle"
            widget: "select"
            options: ["HeaderMain", "HeaderSlide"]
      
      - label: "Footer"
        name: "footer"
        file: "src/pages/settings/footer.md"
        fields:
          - label: "Footer Background"
            name: "footerBackground"
            widget: "select"
            options: ["dark", "light"]
          